version: "2"

linters:
  default: standard
  enable:
    - revive
    - gofumpt
    - misspell
    - unconvert
    - goconst
    - prealloc
    - noctx
    - bodyclose
    - gosec
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
    gosec:
      excludes:
        - G104 # unhandled errors on deferred Close calls
